package:
  name: cset
  version: 24.8.0

source:
  url: https://files.pythonhosted.org/packages/36/5e/9843512e407de724a61621f1573df14941c4b0b92a405c010de598eb5954/cset-24.8.0.tar.gz
  sha256: c2d704877bd7b996a655fe42bbdda434f38d36f061dff3b18c90e4890b652ee3

build:
  noarch: python
  entry_points:
    - cset = CSET:main
  script: "{{ PYTHON }} -m pip install . -vv"
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=64.0
    - setuptools_scm >=8
    - pip >=24.0
  run:
    - python >=3.10
    - numpy
    - iris >=3.6
    - ruamel.yaml >=0.17
    - pygraphviz >=1.11
    - mo_pack >=0.3
    - isodate >=0.6
    - markdown-it-py >=3.0
    - nc-time-axis

test:
  imports:
    - CSET
  commands:
    - pip check
    - cset --version
  requires:
    - pip

about:
  home: https://github.com/MetOffice/CSET
  summary: Convective Scale Evaluation Tool for evaluation and investigation of regional models.
  doc_url: https://metoffice.github.io/CSET
  dev_url: https://github.com/MetOffice/CSET
  license: Apache-2.0
  license_file: LICENCE

extra:
  recipe-maintainers:
    - jfrost-mo
