{% set python_min = "3.10" %}

package:
  name: cset
  version: 25.3.0

source:
  url: https://files.pythonhosted.org/packages/19/21/ec9a357385443a6234c6a4c6965270ed99381c04fdf3427e4b152fb3242e/cset-25.3.0.tar.gz
  sha256: 274f49e42187e9862fe7f26ae03349d8cfcff8bd9a76d4e3c0a04c165834a7c7

build:
  noarch: python
  entry_points:
    - cset = CSET:main
  script: "{{ PYTHON }} -m pip install . -vv"
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0
    - setuptools_scm >=8
    - pip >=24.0
  run:
    - python >={{ python_min }}
    - numpy
    - iris >=3.6
    - ruamel.yaml >=0.17
    - pygraphviz >=1.11
    - mo_pack >=0.3
    - isodate >=0.6
    - markdown-it-py >=3.0
    - nc-time-axis
    - iris-grib

test:
  imports:
    - CSET
  commands:
    - pip check
    - cset --version
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MetOffice/CSET
  summary: Convective Scale Evaluation Tool for evaluation and investigation of regional models.
  doc_url: https://metoffice.github.io/CSET
  dev_url: https://github.com/MetOffice/CSET
  license: Apache-2.0
  license_file: LICENCE

extra:
  recipe-maintainers:
    - jfrost-mo
