package:
  name: cset
  version: 24.4.1

source:
  url: https://files.pythonhosted.org/packages/f3/b1/3c52f7d13328087bcc51f94562ff46c51af6425eb349a3273b6c53665094/cset-24.4.1.tar.gz
  sha256: 8342ad4657fe652cea9d1cdc0614d538e972eec7ced631d7b0b3a37fc365a7a2

build:
  noarch: python
  entry_points:
    - cset = CSET:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=64.0
    - setuptools_scm >=8
    - pip >=23.0
  run:
    - python >=3.10
    - numpy
    - iris >=3.6
    - ruamel.yaml >=0.17
    - pygraphviz >=1.11
    - mo_pack >=0.3
    - isodate >=0.6
    - markdown-it-py >=3.0

test:
  imports:
    - CSET
  commands:
    - pip check
    - cset --version
  requires:
    - pip

about:
  home: https://github.com/MetOffice/CSET
  summary: Convective Scale Evaluation Tool for evaluation and investigation of regional models.
  doc_url: https://metoffice.github.io/CSET
  dev_url: https://github.com/MetOffice/CSET
  license: Apache-2.0
  license_file: LICENCE

extra:
  recipe-maintainers:
    - jfrost-mo
