{% set python_min = "3.10" %}

package:
  name: cset
  version: 25.2.0rc3

source:
  url: https://files.pythonhosted.org/packages/da/b9/3378a7202853d259a90172c80fad758d626887e4e98f2ce068a0b2c65e92/cset-25.2.0rc3.tar.gz
  sha256: ee42def0caf1f1c081d448bec435da69940541d522c224cacdb5208a4a5b7065

build:
  noarch: python
  entry_points:
    - cset = CSET:main
  script: "{{ PYTHON }} -m pip install . -vv"
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0
    - setuptools_scm >=8
    - pip >=24.0
  run:
    - python >={{ python_min }}
    - numpy
    - iris >=3.6
    - ruamel.yaml >=0.17
    - pygraphviz >=1.11
    - mo_pack >=0.3
    - isodate >=0.6
    - markdown-it-py >=3.0
    - nc-time-axis
    - iris-grib

test:
  imports:
    - CSET
  commands:
    - pip check
    - cset --version
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MetOffice/CSET
  summary: Convective Scale Evaluation Tool for evaluation and investigation of regional models.
  doc_url: https://metoffice.github.io/CSET
  dev_url: https://github.com/MetOffice/CSET
  license: Apache-2.0
  license_file: LICENCE

extra:
  recipe-maintainers:
    - jfrost-mo
