{% set name = "CSET" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/CSET-{{ version }}.tar.gz
  sha256: d02c42dab75160ab83062ff6dd1c03385c39bf777b9fab91c0e9c260db3c1d89

build:
  noarch: python
  entry_points:
    - cset = CSET:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0
    - pip >=23.0
  run:
    - python >=3.8
    - numpy
    - iris >=3.5
    - ruamel.yaml >=0.17
    - pygraphviz >=1.11

test:
  imports:
    - CSET
  commands:
    - pip check
    - cset --version
  requires:
    - pip

about:
  home: https://github.com/MetOffice/CSET
  summary: Convective Scale Evaluation Tool for evaluation and investigation of regional models.
  doc_url: https://metoffice.github.io/CSET
  dev_url: https://github.com/MetOffice/CSET
  license: Apache-2.0
  license_file: LICENCE

extra:
  recipe-maintainers:
    - jfrost-mo
