context:
  python_min: "3.12"
  version: "26.2.0"

package:
  name: cset
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/c/cset/cset-${{ version }}.tar.gz
  sha256: 57f394c08b5b2b31f1d7027425c47824d7cd1cb0683c39a28c549fdf9678bc0a

build:
  number: 0
  noarch: python
  script: "python -m pip install . --no-deps -vv"
  python:
    entry_points:
      - cset = CSET:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=64.0
    - setuptools_scm >=8
    - pip >=24.0
  run:
    - python >=${{ python_min }},<3.14
    - numpy
    - iris >=3.14.1
    - ruamel.yaml >=0.17
    - pygraphviz >=1.11
    - mo_pack >=0.3
    - isodate >=0.6
    - markdown-it-py >=3.0
    - nc-time-axis
    - iris-grib
    - scipy
    - scikit-image

tests:
  - python:
      imports:
        - CSET
      pip_check: true
  - script: cset --version
    requirements:
      run:
        - pip
        - python ${{ python_min }}.*

about:
  summary: Community Seamless Evaluation Toolkit for evaluation and investigation of weather and climate models.
  homepage: https://metoffice.github.io/CSET
  repository: https://github.com/MetOffice/CSET
  documentation: https://metoffice.github.io/CSET
  license: Apache-2.0
  license_file: LICENCE

extra:
  recipe-maintainers:
    - daflack
    - jfrost-mo
