context:
  python_min: "3.11"
  version: "25.12.0"

package:
  name: cset
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/c/cset/cset-${{ version }}.tar.gz
  sha256: d36477079ef6b4045fdc2b91e1b10c99ec0dd2088703f694bf68d057d2f8b3a0

build:
  number: 1
  noarch: python
  script: "python -m pip install . --no-deps -vv"
  python:
    entry_points:
      - cset = CSET:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=64.0
    - setuptools_scm >=8
    - pip >=24.0
  run:
    - python >=${{ python_min }},<3.14
    - numpy
    - iris >=3.12.2
    - ruamel.yaml >=0.17
    - pygraphviz >=1.11
    - mo_pack >=0.3
    - isodate >=0.6
    - markdown-it-py >=3.0
    - nc-time-axis
    - iris-grib
    - scipy
    - scikit-image

tests:
  - python:
      imports:
        - CSET
      pip_check: true
  - script: cset --version
    requirements:
      run:
        - pip
        - python ${{ python_min }}.*

about:
  summary: Convective Scale Evaluation Tool for evaluation and investigation of regional models.
  homepage: https://metoffice.github.io/CSET
  repository: https://github.com/MetOffice/CSET
  documentation: https://metoffice.github.io/CSET
  license: Apache-2.0
  license_file: LICENCE

extra:
  recipe-maintainers:
    - jfrost-mo
